---
- hosts: dp-yarn
  gather_facts: false
  become: true
  tasks:
    - name: Installaing python
      raw: bash -c "test -e /usr/bin/python" || (apt update && apt install python -y)

- hosts: dp-yarn
  become: yes
  vars_files:
    - "{{ secrets_path }}"
  tasks:
    - name: Create group
      group: 
        name: hadoop 
        state: present
    - name: Create user
      user: 
        name: hduser 
        comment: "hduser" 
        group: hadoop 
        groups: sudo 
        shell: /bin/bash

- name: Install samza job server
  hosts: "dp-yarn-master"
  become: yes
  vars_files:
    - "{{ secrets_path }}"
  roles:
    - java
    - yarn
    - samza-job-server

- name: Install java on all yarn slaves
  hosts: "dp-yarn-slave"
  become: yes
  vars_files:
    - "{{ secrets_path }}"
  remote_user: hduser
  roles:
    - java
