postgresql_backup_dir: /tmp/postgresql-backup
postgresql_user: postgres
postgresql_backup_azure_container_name: "{{ azure_container }}"
postgresql_backup_azure_storage_account_name: "{{sunbird_management_storage_account_name}}"
postgresql_backup_azure_storage_access_key: "{{sunbird_management_storage_account_key}}"

# Set these vars per environment as show in example below
