---
# file: test.yml
- name: Test that our port is allocated
  wait_for: host={{ hostvars[groups.overload[0]].ansible_host }} port=8081
            connect_timeout=10 state=started
  when: druid_role == "coordinator" 


- name: Test that our port is allocated
  wait_for: host={{ hostvars[groups.overload[0]].ansible_host }} port=8090
            connect_timeout=10 state=started
  when: druid_role == "overlord" 

- name: Test that our port is allocated
  wait_for: host={{ ansible_eth0["ipv4"]["address"] }} port=8083
            connect_timeout=10 state=started
  when: druid_role == "historical" 

- name: Test that our port is allocated
  wait_for: host={{ ansible_eth0["ipv4"]["address"] }} port=8082
            connect_timeout=10 state=started
  when: druid_role == "broker" 

- name: Test that our port is allocated
  wait_for: host={{ ansible_eth0["ipv4"]["address"] }} port=8091
            connect_timeout=10 state=started
  when: druid_role == "middleManager" 

