postgresql_restore_dir: /tmp/postgresql-restore
postgresql_port: 5432
postgresql_cluster_version: 9.5
postgresql_cluster_name: main
postgresql_user: postgres
postgresql_restore_azure_container_name: {{ azure_container }}
postgresql_restore_azure_storage_account_name: {{ azure_account_name }}
postgresql_restore_azure_storage_access_key: {{ azure_storage_secret }}
#postgresql_restore_gzip_file_name: {{ backup_file_name }}

# Set these vars per environment as show in example below
# postgresql_restore_azure_storage_account_name: ntpbackupsstaging

# Pass the parameter
# postgresql_restore_gzip_file_name: <postgresql_restore_gzip_file_name>
