env: dev
kafka_partition_override_size: 5242880

ingestion_kafka_topics:
  - name: telemetry.ingest
    num_of_partitions: 4
    replication_factor: 1

ingestion_kafka_overriden_topics:
  - name: telemetry.ingest
    retention_time: 604800000
    replication_factor: 1

processing_kafka_topics:
  - name: telemetry.raw
    num_of_partitions: 4
    replication_factor: 1
  - name: telemetry.valid
    num_of_partitions: 4
    replication_factor: 1
  - name: telemetry.unique
    num_of_partitions: 8
    replication_factor: 1
  - name: telemetry.duplicate
    num_of_partitions: 1
    replication_factor: 1
  - name: telemetry.sink
    num_of_partitions: 8
    replication_factor: 1
  - name: telemetry.with_location
    num_of_partitions: 8
    replication_factor: 1
  - name: telemetry.de_normalized
    num_of_partitions: 4
    replication_factor: 1
  - name: events.telemetry
    num_of_partitions: 4
    replication_factor: 1
  - name: events.summary
    num_of_partitions: 4
    replication_factor: 1
  - name: telemetry.log
    num_of_partitions: 1
    replication_factor: 1
  - name: analytics.job_queue
    num_of_partitions: 1
    replication_factor: 1
  - name: learning.graph.events
    num_of_partitions: 1
    replication_factor: 1
  - name: pipeline_metrics
    num_of_partitions: 1
    replication_factor: 1
  - name: metrics
    num_of_partitions: 1
    replication_factor: 1
  - name: learning.graph.events.fail
    num_of_partitions: 1
    replication_factor: 1
  - name: analytics_metrics
    num_of_partitions: 1
    replication_factor: 1
  - name: learning.job.request 
    num_of_partitions: 1
    replication_factor: 1
  - name: learning.job.request.fail
    num_of_partitions: 1
    replication_factor: 1
  - name: learning.republish.job.request
    num_of_partitions: 1
    replication_factor: 1
  - name: qrimage.request
    num_of_partitions: 1
    replication_factor: 1
  - name: telemetry.derived
    num_of_partitions: 1
    replication_factor: 1
  - name: telemetry.failed
    num_of_partitions: 1
    replication_factor: 1
  - name: telemetry.malformed
    num_of_partitions: 1
    replication_factor: 1
  - name: telemetry.extractor.failed
    num_of_partitions: 1
    replication_factor: 1
  - name: telemetry.indexer.failed
    num_of_partitions: 1
    replication_factor: 1
  - name: learning.events.failed
    num_of_partitions: 1
    replication_factor: 1
