analytics_user: analytics
analytics_group: analytics
analytics_user_home: /home/{{analytics_user}}
sbin_path: "{{ analytics_user_home }}/sbin"
azure_container_name: "{{secor_azure_container_name}}"
azure_account_key: "{{azure_storage_secret}}"

secor:
  properties: ['secor.azure', 'secor.common', 'secor', 'secor.partition', 'log4j']
  artifact_dir: /mount/secor

secor_service_name:
  channel-telemetry-backup:
    consumer_group: "{{ env }}.telemetry.channel.backup"
    base_path: "channel"
    timestamp_key: "syncts"
    fallback_timestamp_key: "@timestamp"
    topic: "{{ env }}.telemetry.with_location"
    kafka_broker_host: "{{groups['processing-cluster-kafka'][0]}}"
    zookeeper_quorum: "{{groups['processing-cluster-zookeepers']|join(':2181,')}}:2181"
    max_file_size: "100000000"
    max_file_age: "14400"
    ostrich_port: "9991"
    partition_prefix_enabled: "true"
    partition_prefix_key: "eid"
    partition_prefix_mapping: "{\"ME_WORKFLOW_SUMMARY\":\"summary\",\"ME_DEVICE_SUMMARY\":\"summary/device-summary\",\"ME_WORKFLOW_USAGE_METRICS\":\"metrics\",\"ME_CONTENT_USAGE_METRICS\":\"metrics\",\"ME_ITEM_USAGE_METRICS\":\"metrics\",\"ME_GENIE_USAGE_METRICS\":\"metrics\",\"ME_CONTENT_SNAPSHOT_METRICS\":\"metrics\",\"ME_CONCEPT_SNAPSHOT_METRICS\":\"metrics\",\"ME_ASSET_SNAPSHOT_METRICS\":\"metrics\",\"ME_APP_USAGE_METRICS\":\"metrics\",\"ME_CE_USAGE_METRICS\":\"metrics\",\"ME_TEXTBOOK_CREATION_METRICS\":\"metrics\",\"ME_TEXTBOOK_SNAPSHOT_METRICS\":\"metrics\",\"ME_AUTHOR_USAGE_METRICS\":\"metrics\",\"DEFAULT\":\"raw\"}"
    output_file_pattern: "{partition}-{currentTimestamp}.json"
    service_description: "Channel Telemetry Backup"
    service_monitor_schedule_hr: "23"
    service_monitor_schedule_min: "50"
    message_parser: "com.pinterest.secor.parser.ChannelDateMessageParser"
  telemetry-sink-backup:
    consumer_group: "{{ env }}.telemetry.sink.backup"
    base_path: "sink"
    timestamp_key: "syncts"
    fallback_timestamp_key: "@timestamp"
    topic: "{{ env }}.telemetry.sink"
    kafka_broker_host: "{{groups['processing-cluster-kafka'][0]}}"
    zookeeper_quorum: "{{groups['processing-cluster-zookeepers']|join(':2181,')}}:2181"
    max_file_size: "100000000"
    max_file_age: "14400"
    ostrich_port: "9992"
    partition_prefix_enabled: "false"
    partition_prefix_key: ""
    partition_prefix_mapping: "{}"
    output_file_pattern: "{partition}-{currentTimestamp}.json"
    service_description: "Telemetry Sink Backup"
    service_monitor_schedule_hr: "23"
    service_monitor_schedule_min: "50"
    message_parser: "com.pinterest.secor.parser.PatternDateMessageParser"
  derived-telemetry-backup:
    consumer_group: "{{ env }}.telemetry.derived.backup"
    base_path: "derived"
    timestamp_key: "syncts"
    fallback_timestamp_key: "@timestamp"
    topic: "{{ env }}.telemetry.derived"
    kafka_broker_host: "{{groups['processing-cluster-kafka'][0]}}"
    zookeeper_quorum: "{{groups['processing-cluster-zookeepers']|join(':2181,')}}:2181"
    max_file_size: "100000000"
    max_file_age: "600"
    ostrich_port: "9998"
    partition_prefix_enabled: "true"
    partition_prefix_key: "eid"
    partition_prefix_mapping: "{\"ME_SESSION_SUMMARY\":\"ss\",\"ME_DEVICE_SUMMARY\":\"device-summary\",\"ME_ITEM_SUMMARY\":\"is\",\"ME_ASER_SCREEN_SUMMARY\":\"as\",\"ME_LEARNER_ACTIVITY_SUMMARY\":\"las\",\"ME_LEARNER_PROFICIENCY_SUMMARY\":\"lp\",\"ME_LEARNER_CONCEPT_RELEVANCE\":\"lcr\",\"ME_CONTENT_USAGE_SUMMARY\":\"cus\",\"ME_DEVICE_USAGE_SUMMARY\":\"dus\",\"ME_DEVICE_CONTENT_USAGE_SUMMARY\":\"dcus\",\"ME_GENIE_LAUNCH_SUMMARY\":\"gls\",\"ME_GENIE_SESSION_SUMMARY\":\"gss\",\"ME_CONTENT_SIDELOADING_SUMMARY\":\"css\",\"ME_GENIE_USAGE_SUMMARY\":\"genie-launch-summ\",\"ME_ITEM_USAGE_SUMMARY\":\"item-usage-summ\",\"ME_CONTENT_POPULARITY_SUMMARY\":\"cps\",\"ME_STAGE_SUMMARY\":\"sts\",\"ME_GENIE_STAGE_SUMMARY\":\"gsts\",\"ME_GENIE_FUNNEL\":\"gfs\",\"ME_GENIE_FUNNEL_USAGE_SUMMARY\":\"gfa\",\"ME_EOC_RECOMMENDATION_FUNNEL\":\"eocfs\",\"ME_CONTENT_SNAPSHOT_SUMMARY\":\"content-snapshot\",\"ME_CONCEPT_SNAPSHOT_SUMMARY\":\"concept-snapshot\",\"ME_ASSET_SNAPSHOT_SUMMARY\":\"asset-snapshot\",\"ME_APP_SESSION_SUMMARY\":\"app-ss\",\"ME_CE_SESSION_SUMMARY\":\"ce-ss\",\"ME_PUBLISH_PIPELINE_SUMMARY\":\"publish-pipeline-summ\",\"ME_APP_USAGE_SUMMARY\":\"app-usage\",\"ME_CE_USAGE_SUMMARY\":\"ce-usage\",\"ME_AUTHOR_USAGE_SUMMARY\":\"author-usage-summary\",\"ME_TEXTBOOK_SESSION_SUMMARY\":\"textbook-ss\",\"ME_TEXTBOOK_USAGE_SUMMARY\":\"textbook-usage\",\"ME_APP_USAGE_METRICS\":\"eks-creation-metrics/me_app_usage_metrics\",\"ME_ASSET_SNAPSHOT_METRICS\":\"eks-consumption-metrics/me_asset_snapshot_metrics\",\"ME_CE_USAGE_METRICS\":\"eks-creation-metrics/me_ce_usage_metrics\",\"ME_CONCEPT_SNAPSHOT_METRICS\":\"eks-consumption-metrics/me_concept_snapshot_metrics\",\"ME_CONTENT_SNAPSHOT_METRICS\":\"eks-consumption-metrics/me_content_snapshot_metrics\",\"ME_CONTENT_USAGE_METRICS\":\"eks-consumption-metrics/me_content_usage_metrics\",\"ME_GENIE_USAGE_METRICS\":\"eks-consumption-metrics/me_genie_usage_metrics\",\"ME_ITEM_USAGE_METRICS\":\"eks-consumption-metrics/me_item_usage_metrics\",\"ME_TEXTBOOK_SNAPSHOT_METRICS\":\"eks-creation-metrics/me_textbook_snapshot_metrics\",\"ME_TEXTBOOK_CREATION_METRICS\":\"eks-creation-metrics/me_textbook_creation_metrics\",\"ME_AUTHOR_USAGE_METRICS\":\"eks-creation-metrics/me_author_usage_metrics\",\"ME_USAGE_SUMMARY\":\"usage-summary\",\"ME_WORKFLOW_SUMMARY\":\"wfs\",\"ME_WORKFLOW_USAGE_SUMMARY\":\"wfus\",\"ME_DIALCODE_USAGE_SUMMARY\":\"dialus\",\"DEFAULT\":\"me\"}"
    output_file_pattern: "{partition}-{currentTimestamp}.json"
    service_description: "Derived Telemetry Backup"
    service_monitor_schedule_hr: "23"
    service_monitor_schedule_min: "52"
    message_parser: "com.pinterest.secor.parser.PatternDateMessageParser"
  failed-telemetry-backup:
    consumer_group: "{{ env }}.telemetry.failed.backup"
    base_path: "failed"
    timestamp_key: "syncts"
    fallback_timestamp_key: "@timestamp"
    topic: "{{ env }}.telemetry.failed"
    kafka_broker_host: "{{groups['processing-cluster-kafka'][0]}}"
    zookeeper_quorum: "{{groups['processing-cluster-zookeepers']|join(':2181,')}}:2181"
    max_file_size: "100000000"
    max_file_age: "14400"
    ostrich_port: "9997"
    partition_prefix_enabled: "false"
    partition_prefix_key: ""
    partition_prefix_mapping: "{}"
    output_file_pattern: "{partition}-{currentTimestamp}.json"
    service_description: "Failed Telemetry Backup"
    service_monitor_schedule_hr: "23"
    service_monitor_schedule_min: "50"
    message_parser: "com.pinterest.secor.parser.PatternDateMessageParser"
  ingestion-telemetry-backup:
    consumer_group: "{{ env }}.telemetry.ingestion.backup"
    base_path: "ingest"
    timestamp_key: "syncts"
    fallback_timestamp_key: "@timestamp"
    topic: "{{ env }}.telemetry.ingest"
    kafka_broker_host: "{{groups['processing-cluster-kafka'][0]}}"
    zookeeper_quorum: "{{groups['processing-cluster-zookeepers']|join(':2181,')}}:2181"
    max_file_size: "100000000"
    max_file_age: "14400"
    ostrich_port: "9996"
    partition_prefix_enabled: "false"
    partition_prefix_key: ""
    partition_prefix_mapping: "{}"
    output_file_pattern: "{partition}-{currentTimestamp}.json"
    service_description: "Ingestion Telemetry Backup"
    service_monitor_schedule_hr: "23"
    service_monitor_schedule_min: "54"
    message_parser: "com.pinterest.secor.parser.PatternDateMessageParser"
  learning-events-backup:
    consumer_group: "{{ env }}.graph.events.backup"
    base_path: "learning-events"
    timestamp_key: "createdOn"
    fallback_timestamp_key: "@timestamp"
    topic: "{{ env }}.learning.graph.events"
    kafka_broker_host: "{{groups['processing-cluster-kafka'][0]}}"
    zookeeper_quorum: "{{groups['processing-cluster-zookeepers']|join(':2181,')}}:2181"
    max_file_size: "100000000"
    max_file_age: "14400"
    ostrich_port: "9995"
    partition_prefix_enabled: "false"
    partition_prefix_key: ""
    partition_prefix_mapping: "{}"
    output_file_pattern: "{partition}-{currentTimestamp}.json"
    service_description: "Learning Events Backup"
    service_monitor_schedule_hr: "23"
    service_monitor_schedule_min: "56"
    message_parser: "com.pinterest.secor.parser.PatternDateMessageParser"
  raw-telemetry-backup:
    consumer_group: "{{ env }}.telemetry.raw.backup"
    base_path: "raw"
    timestamp_key: "syncts"
    fallback_timestamp_key: "@timestamp"
    topic: "{{ env }}.telemetry.raw"
    kafka_broker_host: "{{groups['processing-cluster-kafka'][0]}}"
    zookeeper_quorum: "{{groups['processing-cluster-zookeepers']|join(':2181,')}}:2181"
    max_file_size: "100000000"
    max_file_age: "14400"
    ostrich_port: "9994"
    partition_prefix_enabled: "false"
    partition_prefix_key: ""
    partition_prefix_mapping: "{}"
    output_file_pattern: "{partition}-{currentTimestamp}.json"
    service_description: "Raw Telemetry Backup"
    service_monitor_schedule_hr: "23"
    service_monitor_schedule_min: "50"
    message_parser: "com.pinterest.secor.parser.PatternDateMessageParser"
  unique-telemetry-backup:
    consumer_group: "{{ env }}.telemetry.unique.backup"
    base_path: "unique"
    timestamp_key: "syncts"
    fallback_timestamp_key: "@timestamp"
    topic: "{{ env }}.telemetry.unique"
    kafka_broker_host: "{{groups['processing-cluster-kafka'][0]}}"
    zookeeper_quorum: "{{groups['processing-cluster-zookeepers']|join(':2181,')}}:2181"
    max_file_size: "100000000"
    max_file_age: "14400"
    ostrich_port: "9993"
    partition_prefix_enabled: "false"
    partition_prefix_key: ""
    partition_prefix_mapping: "{}"
    output_file_pattern: "{partition}-{currentTimestamp}.json"
    service_description: "Unique Telemetry Backup"
    service_monitor_schedule_hr: "23"
    service_monitor_schedule_min: "50"
    message_parser: "com.pinterest.secor.parser.PatternDateMessageParser"
  learning-failed-backup:
    consumer_group: "{{ env }}.learning.failed.events.backup"
    base_path: "learning-failed-events"
    timestamp_key: "ets"
    fallback_timestamp_key: "@timestamp"
    azure_account_name: "{{ secor.azure.account_name }}"
    container_name: "{{ secor.azure.container_name }}"
    azure_account_key: "{{ secor.azure.account_key }}"
    topic: "{{ env }}.learning.events.failed"
    kafka_broker_host: "{{groups['processing-cluster-kafka'][0]}}"
    zookeeper_quorum: "{{groups['processing-cluster-zookeepers']|join(':2181,')}}:2181"
    max_file_size: "100000000"
    max_file_age: "3600"
    ostrich_port: "9999"
    partition_prefix_enabled: "true"
    partition_prefix_key: "jobName"
    partition_prefix_mapping: "{\"publish-pipeline\":\"publish_pipeline\",\"composite-search-indexer\":\"cs_index\",\"DEFAULT\":\"failed_events\"}"
    output_file_pattern: "{partition}-{currentTimestamp}.json"
    service_description: "Learning Failed Backup"
    service_monitor_schedule_hr: "23"
    service_monitor_schedule_min: "52"
    message_parser: "com.pinterest.secor.parser.PatternDateMessageParser"
