version: 2.1
jobs:
  ep-build:
    working_directory: ~/dp/data-pipeline
    machine: true
    steps:
      - checkout:
          path: ~/dp

      - restore_cache:
          key: dependency-cache-{{ checksum "pom.xml" }}
             
      - run: mvn -Dlog4j.configuration=./logs -Dcobertura.report.format=xml clean cobertura:cobertura package

      - save_cache:
          key: dependency-cache-{{ checksum "pom.xml" }}
          paths: ~/.m2

      - run:
          name: sonar
          command: |
             mvn verify sonar:sonar -Dsonar.projectKey=project-sunbird_sunbird-data-pipeline -Dsonar.organization=project-sunbird -Dsonar.host.url=https://sonarcloud.io -Dsonar.coverage.jacoco.xmlReportPaths=/home/circleci/dp/data-pipeline/telemetry-location-updater/target/coverage-reports/jacoco-ut/jacoco.xml,/home/circleci/dp/data-pipeline/telemetry-validator/target/coverage-reports/jacoco-ut/jacoco.xml,/home/circleci/dp/data-pipeline/de-duplication/target/coverage-reports/jacoco-ut/jacoco.xml,/home/circleci/dp/data-pipeline/redis-updater/target/coverage-reports/jacoco-ut/jacoco.xml,/home/circleci/dp/data-pipeline/events-router/target/coverage-reports/jacoco-ut/jacoco.xml,/home/circleci/dp/data-pipeline/telemetry-router/target/coverage-reports/jacoco-ut/jacoco.xml,/home/circleci/dp/data-pipeline/druid-events-validator/target/coverage-reports/jacoco-ut/jacoco.xml,/home/circleci/dp/data-pipeline/telemetry-extractor/target/coverage-reports/jacoco-ut/jacoco.xml,/home/circleci/dp/data-pipeline/de-normalization/target/coverage-reports/jacoco-ut/jacoco.xml
#workflow step           
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - ep-build
