remote_user: druid
broker_port: 8082
druid_home: /home/druid
druid_schema:
 - telemetry_index_kafka
 - summary_index_kafka
 - log_index_kafka
 - telemetry_feedback_index_kafka
event_types:
 - telemetry-events
 - summary-events
 - telemetry-log-events
 - telemetry-feedback-events
