remote_user: druid
broker_port: 8082
druid_home: /home/druid
desktop_pdata_id: "{{env}}.sunbird.desktop"

ingestion_spec_configs:
  raw_telemetry_events:
    minTaskMemory: 200m
    maxTaskMemory: 400m

raw_offline_desktop_taskcount: 1
raw_summary_events_taskcount: 1
raw_telemetry_events_taskcount: 1
raw_telemetry_feedback_events_taskcount: 1
rollup_error_hourly_syncts_taskcount: 1
rollup_summary_distinct_counts_taskcount: 1
rollup_summary_syncts_taskcount: 1
rollup_telemetry_audit_syncts_taskcount: 1
rollup_telemetry_hourly_syncts_taskcount: 1
rollup_telemetry_syncts_taskcount: 1
rollup_tpd_hourly_taskcount: 1
