apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager-rest
spec:
  type: NodePort
  ports:
  - name: rest
    nodePort: 30509
    port: 8081
    protocol: TCP
    # port: 8081
    targetPort: 8081
  selector:
    app: flink
    component: jobmanager

# apiVersion: v1
# kind: Service
# metadata:
#   namespace: flink-namespace
#   name: flink-jobmanager-rest
# spec:
#   type: LoadBalancer
#   ports:
#   - name: rest
#     port: 12000
#     protocol: TCP
#     targetPort: 8081
#   selector:
#     app: flink
#     component: jobmanager