spark_folder: /usr/hdp/current/spark2-client
guava_version: 19.0
log4j_version: 2.16.0
spark_redis_version: 2.5.0
guava_default_jre_version: 28.0-jre
guava_jre_version: 24.1.1-jre
jedis_version: 3.2.0
zip4j_version: 2.6.2
guice_default_version: 4.0
guice_version: 3.0
guava_url: https://repo1.maven.org/maven2/com/google/guava/guava/{{guava_version}}/guava-{{guava_version}}.jar
guava_jre_url: https://repo1.maven.org/maven2/com/google/guava/guava/{{guava_jre_version}}/guava-{{guava_jre_version}}.jar
log4j_core_url: https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-core/{{log4j_version}}/log4j-core-{{log4j_version}}.jar
log4j_api_url: https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-api/{{log4j_version}}/log4j-api-{{log4j_version}}.jar
spark_redis_url: https://repo1.maven.org/maven2/com/redislabs/spark-redis_2.11/{{spark_redis_version}}/spark-redis_2.11-{{spark_redis_version}}.jar
jedis_url: https://repo1.maven.org/maven2/redis/clients/jedis/{{jedis_version}}/jedis-{{jedis_version}}.jar
zip4j_url: https://repo1.maven.org/maven2/net/lingala/zip4j/zip4j/{{zip4j_version}}/zip4j-{{zip4j_version}}.jar
guice_url: https://repo1.maven.org/maven2/com/google/inject/guice/{{guice_version}}/guice-{{guice_version}}.jar
guice_servlet_url: https://repo1.maven.org/maven2/com/google/inject/extensions/guice-servlet/{{guice_version}}/guice-servlet-{{guice_version}}.jar