---
- name: Add Java repository to sources
  action: apt_repository repo='ppa:webupd8team/java'
  sudo: yes

- name: Autoaccept license for Java
  action: shell echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
  sudo: yes

- name: Update APT package cache
  action: apt update_cache=yes
  sudo: yes

- name: Install Java 7
  action: apt pkg=oracle-java7-installer state=latest install_recommends=yes
  sudo: yes

- name: Set Java 7 Env
  action: apt pkg=oracle-java7-set-default state=latest install_recommends=yes
  sudo: yes