---
- hosts: "{{remote}}"
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
  become: yes
  become_user: "{{ analytics_user }}"
  environment:
    AZURE_STORAGE_ACCOUNT: "{{sunbird_private_storage_account_name}}"
    AZURE_STORAGE_KEY: "{{sunbird_private_storage_account_key}}"
    OCI_CLI_AUTH: "instance_principal"
  roles:
   - data-products-deploy
