---
- hosts: "{{remote}}"
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
  become: yes
  become_user: "{{ analytics_user }}"
  environment:
    AZURE_STORAGE_ACCOUNT: "{{cloud_private_storage_accountname}}"
    AZURE_STORAGE_KEY: "{{cloud_private_storage_secret}}"
  roles:
   - data-products-deploy
