---
zookeeper_version: 3.6.3
zookeeper_url: "https://downloads.apache.org/zookeeper/stable/apache-zookeeper-{{ zookeeper_version }}-bin.tar.gz"
zookeeper_port: 2181
zk_jvm_opts: "-Xms128m -Xmx128m"
verify: True
apt_cache_timeout: 3600
init_limit: 5
sync_limit: 2
tick_time: 2000
zoo_id: 1
maxclinetconnection_limit: 200
zookeeper_data_dir: /opt/zookeeper
log_dir: /var/log/zookeeper
client_port: "{{ zookeeper_port }}"
zookeeper_group: "{{ groups['zookeeper'] }}"
zookeeper_user: zookeeper
zookeeper_dir: /opt
zookeeper_systemd_service: /etc/systemd/system/zookeeper.service
# List of dict (i.e. {zookeeper_hosts:[{host:,id:},{host:,id:},...]})
# zookeeper_hosts:
#   - host: "{{inventory_hostname}}" # the machine running
#     id: 1
