env: dev
kafka_partition_override_size: 5242880
dp_downstream_kafka_max_message_bytes: 1572864

ingestion_kafka_topics:
  - name: telemetry.ingestion
    num_of_partitions: 2
    replication_factor: 1
  - name: events.deviceprofile
    num_of_partitions: 2
    replication_factor: 1

ingestion_kafka_overriden_topics:
  - name: telemetry.ingestion
    retention_time: 259200000
    replication_factor: 1
    max_message_bytes: 5242880
  - name: events.deviceprofile
    retention_time: 172800000
    replication_factor: 1

processing_kafka_overriden_topics:
  - name: analytics.job_queue
    retention_time: 172800000
    replication_factor: 1
  - name: analytics_metrics
    retention_time: 172800000
    replication_factor: 1
  - name: druid.events.error
    retention_time: 172800000
    replication_factor: 1
  - name: druid.events.log
    retention_time: 172800000
    replication_factor: 1
  - name: druid.events.summary
    retention_time: 172800000
    replication_factor: 1
  - name: druid.events.telemetry
    retention_time: 172800000
    replication_factor: 1
  - name: events.deviceprofile
    retention_time: 172800000
    replication_factor: 1
  - name: prom.monitoring.metrics
    retention_time: 172800000
    replication_factor: 1
  - name: telemetry.assess
    retention_time: 172800000
    replication_factor: 1
  - name: telemetry.assess.failed
    retention_time: 172800000
    replication_factor: 1
  - name: telemetry.assess.raw
    retention_time: 172800000
    replication_factor: 1
  - name: telemetry.audit
    retention_time: 172800000
    replication_factor: 1
  - name: telemetry.denorm 
    retention_time: 172800000
    replication_factor: 1
  - name: telemetry.derived
    retention_time: 172800000
    replication_factor: 1
  - name: telemetry.derived.unique
    retention_time: 172800000
    replication_factor: 1
  - name: telemetry.duplicate
    retention_time: 172800000
    replication_factor: 1
  - name: telemetry.error
    retention_time: 172800000
    replication_factor: 1
  - name: telemetry.extractor.duplicate
    retention_time: 172800000
    replication_factor: 1
  - name: telemetry.extractor.failed
    retention_time: 172800000
    replication_factor: 1
  - name: telemetry.failed
    retention_time: 172800000
    replication_factor: 1
  - name: telemetry.ingest
    retention_time: 172800000
    replication_factor: 1
  - name: telemetry.metrics
    retention_time: 172800000
    replication_factor: 1
  - name: telemetry.raw
    retention_time: 172800000
    replication_factor: 1
  - name: telemetry.unique
    retention_time: 172800000
    replication_factor: 1
  - name: telemetry.unique.latest
    retention_time: 172800000
    replication_factor: 1
  - name: telemetry.unique.primary
    retention_time: 172800000
    replication_factor: 1
  - name: telemetry.unique.secondary
    retention_time: 172800000
    replication_factor: 1
  - name: ml.observation.raw
    retention_time: 172800000
    replication_factor: 1
  - name: ml.observation.druid
    retention_time: 172800000
    replication_factor: 1

processing_kafka_topics:
  - name: analytics.job_queue
    num_of_partitions: 1
    replication_factor: 1
  - name: analytics_metrics
    num_of_partitions: 1
    replication_factor: 1
  - name: druid.events.error
    num_of_partitions: 2
    replication_factor: 1
  - name: druid.events.log
    num_of_partitions: 2
    replication_factor: 1
  - name: druid.events.summary
    num_of_partitions: 2
    replication_factor: 1
  - name: druid.events.telemetry
    num_of_partitions: 2
    replication_factor: 1
  - name: events.deviceprofile
    num_of_partitions: 2
    replication_factor: 1
  - name: prom.monitoring.metrics
    num_of_partitions: 1
    replication_factor: 1
  - name: telemetry.assess
    num_of_partitions: 2
    replication_factor: 1
  - name: telemetry.assess.failed
    num_of_partitions: 2
    replication_factor: 1
  - name: telemetry.assess.raw
    num_of_partitions: 2
    replication_factor: 1
  - name: telemetry.audit
    num_of_partitions: 2
    replication_factor: 1
  - name: telemetry.denorm 
    num_of_partitions: 2
    replication_factor: 1
  - name: telemetry.derived
    num_of_partitions: 2
    replication_factor: 1
  - name: telemetry.derived.unique
    num_of_partitions: 2
    replication_factor: 1
  - name: telemetry.duplicate
    num_of_partitions: 2
    replication_factor: 1
  - name: telemetry.error
    num_of_partitions: 1
    replication_factor: 1
  - name: telemetry.extractor.duplicate
    num_of_partitions: 2
    replication_factor: 1
  - name: telemetry.extractor.failed
    num_of_partitions: 2
    replication_factor: 1
  - name: telemetry.failed
    num_of_partitions: 2
    replication_factor: 1
  - name: telemetry.ingest
    num_of_partitions: 2
    replication_factor: 1
  - name: telemetry.metrics
    num_of_partitions: 2
    replication_factor: 1
  - name: telemetry.raw
    num_of_partitions: 2
    replication_factor: 1
  - name: telemetry.unique
    num_of_partitions: 2
    replication_factor: 1
  - name: telemetry.unique.latest
    num_of_partitions: 2
    replication_factor: 1
  - name: telemetry.unique.primary
    num_of_partitions: 2
    replication_factor: 1
  - name: telemetry.unique.secondary
    num_of_partitions: 2
    replication_factor: 1
  - name: druid.events.log
    num_of_partitions: 1
    replication_factor: 1
  - name: druid.events.telemetry
    num_of_partitions: 1
    replication_factor: 1
  - name: druid.events.summary
    num_of_partitions: 1
    replication_factor: 1
  - name: ml.observation.raw
    num_of_partitions: 1
    replication_factor: 1
  - name: ml.observation.druid
    num_of_partitions: 1
    replication_factor: 1
